# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 03:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('tweet_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('json_blob', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tweet_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TweetSentiment',
            fields=[
                ('tweet_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='services.Tweet')),
                ('cleaned_tweet', models.TextField()),
                ('frequency', models.IntegerField()),
                ('sentiment', models.IntegerField(choices=[('positive', 2), ('neutral', 1), ('negative', 0)])),
            ],
        ),
    ]
